### ISSUE TITLE
null pointer reference with -rabbitmq

### ISSUE THREAD

**Issue by lukaf** [trayio/inventory#1]
Selecting rabbitmq output with no instances matching the group (-rabbitmq-tag-value) results in referencing a null pointer:

```
$ inventory -rabbitmq
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x48 pc=0x4051de]

goroutine 1 [running]:
main.main()
        /home/luka/golang/src/github.com/trayio/inventory/main.go:289 +0x372e

goroutine 101 [select]:
net/http.(*persistConn).writeLoop(0xc820168000)
        /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:686 +0xc9d
```

**Comment by lukaf** [comment]
Fixed with https://github.com/trayio/inventory/commit/9bd330087d181db8946ab5f7b455e9e2aebd65ab
